/**
 * UI shell — the DOM chrome around the canvas: a full-viewport main-menu
 * screen (boot lands here), a slim in-game control bar (menu/pause/new-game/
 * sound/level-info), and a themes panel. Built entirely with
 * `document.createElement` calls appended under `#ui-root`; `index.html`
 * stays declarative-minimal.
 *
 * Nibble is offline-only and single-device: this layer holds no reference to
 * persistence at all (no adapter, no mode id) — it is purely display state
 * plus abstract callbacks. Play/pause/restart/theme-select/mute-toggle/
 * menu-open/menu-close are forwarded as abstract callbacks; this module
 * never touches engine, level, theme-registry, or audio internals itself —
 * `ModeOption` and `ThemeOption` are plain display data owned by this layer,
 * and the sound control only reports clicks: the caller (main.ts) owns the
 * actual `SoundPlayer` and any persisted mute preference. The shell knows
 * nothing about what a mode *means* (level config, rules, engine wiring) —
 * it only renders the option list and reports the selected id upward via
 * `onPlay`; the caller owns starting/restarting games. Every theme is
 * unlocked and selectable — the shell has no notion of locked cosmetics.
 *
 * On-screen D-pad: a `.nibble-dpad` cluster of four directional buttons,
 * hidden by default and shown via `setTouchControls(true)`. Same
 * caller-owns-the-decision pattern as sound — this module only renders the
 * pad and the menu's "TOUCH PAD" toggle row and reports `onDirection` /
 * `onTouchControlsToggle` upward; main.ts decides whether the pad should be
 * on (persisted setting / pointer coarseness) and forwards `onDirection`
 * into the same `InputController.pushTurn()` queue the keyboard/swipe
 * handlers use. `PadDirection` is structurally identical to the engine's
 * `Direction` but declared locally so this layer never imports engine types
 * for a purely presentational control.
 *
 * Screen layering (all under `#ui-root`, all `position: fixed`):
 *   - the menu screen sits at z-index 5, visible by default at creation
 *     (boot lands on the menu) and toggled via `[hidden]`.
 *   - the themes panel sits at z-index 10, i.e. ABOVE the menu, so choosing
 *     "Themes" from the menu opens the exact same panel used from in-game,
 *     stacked on top of the menu layer.
 *   - the slim in-game control bar is normal flow (not fixed), matching the
 *     canvas width, and is only meaningful while the menu is hidden.
 *
 * Accessibility: every button carries an `aria-label`; the menu and the
 * themes panel are `role="dialog"` with `aria-modal="true"` and either
 * `aria-label` (menu) or `aria-labelledby` (panel, pointing at its title).
 * Showing the menu or opening the panel moves focus to a sensible first
 * control and traps Tab within it; Escape closes/hides it (and stops the
 * keydown from bubbling to the page-level pause handler in `input.ts`);
 * closing restores focus to whichever control opened it. The level-info
 * label is `aria-live="polite"` so level changes are announced.
 */

const STYLE_ELEMENT_ID = 'nibble-ui-style'
const FOCUSABLE_SELECTOR =
  'button:not([disabled]), [href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])'
/** Menu backdrop artwork generated by the art-pipeline agent; missing file falls back to the CSS background-color below (no JS load check needed). */
const MENU_BACKDROP_URL = `${import.meta.env.BASE_URL}assets/backgrounds/menu/bg.png`

/** Display-only mode entry for the menu's PLAY rows. Opaque id to this layer. */
export interface ModeOption {
  readonly id: string
  readonly name: string
}

/** Display-only theme entry for the theme-select panel; ladder order. */
export interface ThemeOption {
  readonly id: string
  readonly name: string
}

/**
 * Structurally identical to the engine's `Direction` — declared locally so
 * this layer stays decoupled from `src/engine` for what is purely a
 * presentational on-screen control.
 */
export type PadDirection = 'up' | 'down' | 'left' | 'right'

export interface UiShell {
  /** Reflect paused/running state on the pause button label. */
  setPaused(paused: boolean): void
  /** Reflect the active selection in the themes panel (updates the marked row / stored id even while closed). */
  setActiveTheme(id: string): void
  /** Reflect the active selection as the menu's marked PLAY row. */
  setActiveMode(id: string): void
  /** Set/replace the small non-interactive level-info bar label (e.g. "LV 3/8"); null hides it. */
  setLevelInfo(text: string | null): void
  /** Reflect mute state on the sound control (e.g. "SOUND: ON/OFF"), in both the bar and the menu. Caller owns the SoundPlayer + persistence. */
  setMuted(muted: boolean): void
  /** Show/hide the on-screen D-pad and sync the menu's "TOUCH PAD: ON/OFF" label. Caller (main.ts) owns the persisted preference. */
  setTouchControls(enabled: boolean): void
  /** Replace the theme list; re-renders rows (open or not) and preserves the active marker. */
  updateThemes(themes: readonly ThemeOption[]): void
  /** Programmatic open of the main menu screen. Does NOT fire onMenuOpen (that's reserved for the in-game MENU button). */
  showMenu(): void
  /** Remove all DOM this shell created and detach listeners. */
  dispose(): void
}

export function createUiShell(opts: {
  modes: readonly ModeOption[]
  activeModeId: string
  themes: readonly ThemeOption[]
  activeThemeId: string
  onThemeSelect(id: string): void
  onPauseToggle(): void
  onRestart(): void
  /** User clicked the sound control (bar or menu). The shell shows the control only; main.ts owns the SoundPlayer + persisted preference. */
  onMuteToggle(): void
  /** A D-pad arrow was pressed. Forwarded verbatim; main.ts routes it into the InputController's turn queue. */
  onDirection(dir: PadDirection): void
  /** The menu's "TOUCH PAD" toggle row was clicked. The shell shows the control only; main.ts owns the persisted preference and decides the resulting state via setTouchControls(). */
  onTouchControlsToggle(): void
  /** User picked a mode's PLAY entry in the menu. The shell hides the menu itself before calling this. */
  onPlay(modeId: string): void
  /** The menu became visible via the in-game MENU button. main.ts pauses the live run. */
  onMenuOpen(): void
  /** The menu was dismissed without choosing (Escape / close control / RESUME). main.ts resumes. */
  onMenuClose(): void
}): UiShell {
  const {
    onThemeSelect,
    onPauseToggle,
    onRestart,
    onMuteToggle,
    onDirection,
    onTouchControlsToggle,
    onPlay,
    onMenuOpen,
    onMenuClose,
  } = opts
  let modes = opts.modes
  let themes = opts.themes
  let activeModeId = opts.activeModeId
  let activeThemeId = opts.activeThemeId

  injectStyles()

  const root = document.getElementById('ui-root')
  if (!root) throw new Error('#ui-root not found')

  // --- dialog helper ------------------------------------------------------
  // Shared wiring for every overlay panel below: role="dialog" + aria-modal,
  // aria-labelledby -> the panel's own title, Escape-to-close (stopped from
  // bubbling so input.ts's page-level Escape-pauses-game handler never
  // fires while a panel is open), a simple first/last-sentinel focus trap,
  // and focus save/restore so closing a panel returns focus to whichever
  // control opened it.
  let dialogUidCounter = 0

  function makeDialog(overlay: HTMLDivElement, panel: HTMLDivElement, title: HTMLHeadingElement): {
    open(opener: HTMLElement | null, focusTarget?: HTMLElement): void
    close(): void
  } {
    if (!title.id) title.id = `nibble-dialog-title-${++dialogUidCounter}`
    panel.setAttribute('role', 'dialog')
    panel.setAttribute('aria-modal', 'true')
    panel.setAttribute('aria-labelledby', title.id)
    panel.tabIndex = -1

    let lastOpener: HTMLElement | null = null

    function focusables(): HTMLElement[] {
      return Array.from(panel.querySelectorAll<HTMLElement>(FOCUSABLE_SELECTOR)).filter(
        (el) => !el.hidden && el.offsetParent !== null,
      )
    }

    function onKeydown(event: KeyboardEvent): void {
      if (event.key === 'Escape') {
        event.stopPropagation()
        event.preventDefault()
        close()
        return
      }
      if (event.key === 'Tab') {
        const items = focusables()
        if (items.length === 0) return
        const first = items[0]
        const last = items[items.length - 1]
        if (event.shiftKey && document.activeElement === first) {
          event.preventDefault()
          last.focus()
        } else if (!event.shiftKey && document.activeElement === last) {
          event.preventDefault()
          first.focus()
        }
      }
    }

    function open(opener: HTMLElement | null, focusTarget?: HTMLElement): void {
      lastOpener = opener
      overlay.hidden = false
      overlay.addEventListener('keydown', onKeydown)
      const target = focusTarget ?? focusables()[0] ?? panel
      target.focus()
    }

    function close(): void {
      overlay.hidden = true
      overlay.removeEventListener('keydown', onKeydown)
      lastOpener?.focus()
      lastOpener = null
    }

    return { open, close }
  }

  // --- main menu screen ---------------------------------------------------
  // Full-viewport layer, z-index BELOW the themes panel (5 vs. its 10) so
  // Themes stacks visually above the menu and returns focus to the menu row
  // that opened it. Visible by default: boot lands here.
  const menuLayer = document.createElement('div')
  menuLayer.className = 'nibble-menu'
  menuLayer.setAttribute('role', 'dialog')
  menuLayer.setAttribute('aria-modal', 'true')
  menuLayer.setAttribute('aria-label', 'Main menu')
  menuLayer.tabIndex = -1
  // The scrim gradient itself lives once in the .nibble-menu CSS rule below;
  // only the backdrop URL is set here so it stays the single source of truth
  // for MENU_BACKDROP_URL while the CSS owns the readability treatment.
  menuLayer.style.setProperty('--nibble-menu-backdrop', `url("${MENU_BACKDROP_URL}")`)

  const menuColumn = document.createElement('div')
  menuColumn.className = 'nibble-menu-column'

  const menuLogo = document.createElement('img')
  menuLogo.className = 'nibble-menu-logo'
  menuLogo.src = `${import.meta.env.BASE_URL}icons/icon.svg`
  menuLogo.alt = ''
  menuLogo.setAttribute('aria-hidden', 'true')

  const menuWordmark = document.createElement('h1')
  menuWordmark.className = 'nibble-menu-wordmark'
  menuWordmark.textContent = 'NIBBLE'

  const menuTagline = document.createElement('p')
  menuTagline.className = 'nibble-menu-tagline'
  menuTagline.textContent = 'the classic snake, reborn'

  const menuButtons = document.createElement('div')
  menuButtons.className = 'nibble-menu-buttons'

  const menuModeButtons = new Map<string, HTMLButtonElement>()

  function renderMenuModeButtons(): void {
    menuModeButtons.forEach((button) => button.remove())
    menuModeButtons.clear()

    modes.forEach((mode) => {
      const button = document.createElement('button')
      button.type = 'button'
      button.className = 'nibble-menu-btn nibble-menu-btn-play'
      button.addEventListener('click', () => {
        hideMenu()
        onPlay(mode.id)
      })
      // Insert PLAY rows before the fixed THEMES/SOUND block.
      menuButtons.insertBefore(button, menuSecondaryButtons)
      menuModeButtons.set(mode.id, button)
    })

    syncMenuModeLabels()
  }

  function syncMenuModeLabels(): void {
    modes.forEach((mode) => {
      const button = menuModeButtons.get(mode.id)
      if (!button) return
      const isActive = mode.id === activeModeId
      button.textContent = `PLAY ${mode.name.toUpperCase()}`
      button.classList.toggle('nibble-menu-btn-active', isActive)
      button.setAttribute(
        'aria-label',
        isActive ? `Play ${mode.name} (current mode)` : `Play ${mode.name}`,
      )
    })
  }

  // Sentinel marking where the fixed (non-mode) rows begin, so PLAY rows can
  // always be (re)inserted before it regardless of how many modes there are.
  const menuSecondaryButtons = document.createElement('div')
  menuSecondaryButtons.className = 'nibble-menu-secondary'
  menuSecondaryButtons.hidden = true

  const menuThemesButton = document.createElement('button')
  menuThemesButton.type = 'button'
  menuThemesButton.className = 'nibble-menu-btn'
  menuThemesButton.textContent = 'THEMES'
  menuThemesButton.setAttribute('aria-label', 'Choose theme')
  menuThemesButton.addEventListener('click', () => openThemes(menuThemesButton))

  const menuSoundButton = document.createElement('button')
  menuSoundButton.type = 'button'
  menuSoundButton.className = 'nibble-menu-btn'
  menuSoundButton.addEventListener('click', () => onMuteToggle())

  const menuTouchPadButton = document.createElement('button')
  menuTouchPadButton.type = 'button'
  menuTouchPadButton.className = 'nibble-menu-btn'
  menuTouchPadButton.addEventListener('click', () => onTouchControlsToggle())

  menuButtons.append(menuSecondaryButtons)
  menuButtons.append(menuThemesButton, menuSoundButton, menuTouchPadButton)

  const menuResumeButton = document.createElement('button')
  menuResumeButton.type = 'button'
  menuResumeButton.className = 'nibble-menu-resume'
  menuResumeButton.textContent = 'RESUME'
  menuResumeButton.setAttribute('aria-label', 'Resume without choosing')
  menuResumeButton.addEventListener('click', () => {
    hideMenu()
    onMenuClose()
  })

  menuColumn.append(menuLogo, menuWordmark, menuTagline, menuButtons, menuResumeButton)
  menuLayer.appendChild(menuColumn)
  root.appendChild(menuLayer)

  renderMenuModeButtons()

  let menuOpenerForFocusRestore: HTMLElement | null = null

  function menuFocusables(): HTMLElement[] {
    return Array.from(menuLayer.querySelectorAll<HTMLElement>(FOCUSABLE_SELECTOR)).filter(
      (el) => !el.hidden && el.offsetParent !== null,
    )
  }

  function onMenuKeydown(event: KeyboardEvent): void {
    if (event.key === 'Escape') {
      event.stopPropagation()
      event.preventDefault()
      hideMenu()
      onMenuClose()
      return
    }
    if (event.key === 'Tab') {
      const items = menuFocusables()
      if (items.length === 0) return
      const first = items[0]
      const last = items[items.length - 1]
      if (event.shiftKey && document.activeElement === first) {
        event.preventDefault()
        last.focus()
      } else if (!event.shiftKey && document.activeElement === last) {
        event.preventDefault()
        first.focus()
      }
    }
  }

  /** Show the menu layer and move focus in. Shared by showMenu() and the bar's MENU button; callers decide whether to fire onMenuOpen. */
  function displayMenu(opener: HTMLElement | null): void {
    menuOpenerForFocusRestore = opener
    menuLayer.hidden = false
    menuLayer.addEventListener('keydown', onMenuKeydown)
    const firstModeButton = modes.length > 0 ? menuModeButtons.get(modes[0].id) : undefined
    const target = firstModeButton ?? menuFocusables()[0] ?? menuLayer
    target.focus()
  }

  function hideMenu(): void {
    menuLayer.hidden = true
    menuLayer.removeEventListener('keydown', onMenuKeydown)
    menuOpenerForFocusRestore?.focus()
    menuOpenerForFocusRestore = null
  }

  // --- control bar ---------------------------------------------------
  // Declutered: the menu now owns navigation (mode choice, themes). The
  // in-game bar is just MENU | Pause | New Game | Sound | level-info.
  const bar = document.createElement('div')
  bar.className = 'nibble-bar'

  const menuButton = document.createElement('button')
  menuButton.type = 'button'
  menuButton.className = 'nibble-btn'
  menuButton.textContent = 'Menu'
  menuButton.setAttribute('aria-label', 'Open main menu')
  menuButton.addEventListener('click', () => {
    displayMenu(menuButton)
    onMenuOpen()
  })

  const pauseButton = document.createElement('button')
  pauseButton.type = 'button'
  pauseButton.className = 'nibble-btn'
  pauseButton.textContent = 'Pause'
  pauseButton.setAttribute('aria-label', 'Pause game')
  pauseButton.addEventListener('click', () => onPauseToggle())

  const soundButton = document.createElement('button')
  soundButton.type = 'button'
  soundButton.className = 'nibble-btn'
  soundButton.addEventListener('click', () => onMuteToggle())

  const restartButton = document.createElement('button')
  restartButton.type = 'button'
  restartButton.className = 'nibble-btn'
  restartButton.textContent = 'New Game'
  restartButton.setAttribute('aria-label', 'Start new game')
  restartButton.addEventListener('click', () => onRestart())

  const levelInfoLabel = document.createElement('span')
  levelInfoLabel.className = 'nibble-level-info'
  levelInfoLabel.setAttribute('aria-label', 'Level info')
  levelInfoLabel.setAttribute('aria-live', 'polite')
  levelInfoLabel.hidden = true

  bar.append(menuButton, pauseButton, soundButton, restartButton, levelInfoLabel)
  root.appendChild(bar)

  // --- on-screen D-pad -------------------------------------------------
  // Diamond cluster of four direction buttons. Hidden by default ([hidden]);
  // main.ts decides when to reveal it via setTouchControls(). Sits below the
  // bar in normal document flow (portrait/normal layouts); a landscape media
  // query below repositions it to a fixed thumb-zone corner instead.
  const dpad = document.createElement('div')
  dpad.className = 'nibble-dpad'
  dpad.hidden = true

  function createPadButton(dir: PadDirection, label: string, glyph: string): HTMLButtonElement {
    const button = document.createElement('button')
    button.type = 'button'
    // The per-direction class also carries the grid-area placement in CSS
    // (single source of truth for the diamond layout — see .nibble-dpad-btn-*
    // below), so this class list positions AND styles the button.
    button.className = `nibble-dpad-btn nibble-dpad-btn-${dir}`
    button.textContent = glyph
    button.setAttribute('aria-label', label)
    // pointerdown (not click): a turn is a single intent and latency matters.
    // preventDefault kills the synthesized ghost click/focus flicker that
    // otherwise follows a touch pointerdown on some browsers.
    button.addEventListener('pointerdown', (event) => {
      event.preventDefault()
      button.classList.add('nibble-dpad-btn-pressed')
      onDirection(dir)
    })
    const clearPressed = (): void => button.classList.remove('nibble-dpad-btn-pressed')
    button.addEventListener('pointerup', clearPressed)
    button.addEventListener('pointerleave', clearPressed)
    button.addEventListener('pointercancel', clearPressed)
    // No 'click' handler by design — pointerdown already fired the turn;
    // handling click too would double-fire on pointer devices that also
    // synthesize a click after pointerup.
    return button
  }

  const dpadUp = createPadButton('up', 'Turn up', '▲')
  const dpadLeft = createPadButton('left', 'Turn left', '◀')
  const dpadRight = createPadButton('right', 'Turn right', '▶')
  const dpadDown = createPadButton('down', 'Turn down', '▼')

  dpad.append(dpadUp, dpadLeft, dpadRight, dpadDown)
  root.appendChild(dpad)

  function syncTouchPadVisibility(enabled: boolean): void {
    dpad.hidden = !enabled
    document.documentElement.classList.toggle('nibble-touchpad-on', enabled)
  }

  function syncSoundLabel(muted: boolean): void {
    const text = muted ? 'SOUND: OFF' : 'SOUND: ON'
    const ariaLabel = muted ? 'Sound is off. Click to turn on.' : 'Sound is on. Click to turn off.'
    soundButton.textContent = text
    soundButton.setAttribute('aria-label', ariaLabel)
    soundButton.setAttribute('aria-pressed', String(!muted))
    menuSoundButton.textContent = text
    menuSoundButton.setAttribute('aria-label', ariaLabel)
    menuSoundButton.setAttribute('aria-pressed', String(!muted))
  }
  syncSoundLabel(false)

  function syncTouchPadLabel(enabled: boolean): void {
    const text = enabled ? 'TOUCH PAD: ON' : 'TOUCH PAD: OFF'
    const ariaLabel = enabled
      ? 'On-screen touch pad is on. Click to turn off.'
      : 'On-screen touch pad is off. Click to turn on.'
    menuTouchPadButton.textContent = text
    menuTouchPadButton.setAttribute('aria-label', ariaLabel)
    menuTouchPadButton.setAttribute('aria-pressed', String(enabled))
  }
  syncTouchPadLabel(false)

  // --- themes panel -----------------------------------------------------
  const themesOverlay = document.createElement('div')
  themesOverlay.className = 'nibble-overlay'
  themesOverlay.hidden = true

  const themesPanel = document.createElement('div')
  themesPanel.className = 'nibble-panel'

  const themesTitle = document.createElement('h2')
  themesTitle.className = 'nibble-panel-title'
  themesTitle.textContent = 'Themes'

  const themesList = document.createElement('ol')
  themesList.className = 'nibble-themes-list'

  const themesCloseButton = document.createElement('button')
  themesCloseButton.type = 'button'
  themesCloseButton.className = 'nibble-btn'
  themesCloseButton.textContent = 'Close'
  themesCloseButton.setAttribute('aria-label', 'Close theme selection')
  themesCloseButton.addEventListener('click', () => closeThemes())

  themesPanel.append(themesTitle, themesList, themesCloseButton)
  themesOverlay.appendChild(themesPanel)
  root.appendChild(themesOverlay)

  const themesDialog = makeDialog(themesOverlay, themesPanel, themesTitle)

  const themeRowButtons = new Map<string, HTMLButtonElement>()

  function renderThemeRows(): void {
    themesList.replaceChildren()
    themeRowButtons.clear()

    if (themes.length === 0) {
      const empty = document.createElement('li')
      empty.className = 'nibble-themes-empty'
      empty.textContent = 'No themes available.'
      themesList.appendChild(empty)
      return
    }

    themes.forEach((theme) => {
      const row = document.createElement('li')
      row.className = 'nibble-themes-row'

      const rowButton = document.createElement('button')
      rowButton.type = 'button'
      rowButton.className = 'nibble-theme-btn'
      rowButton.addEventListener('click', () => {
        onThemeSelect(theme.id)
        closeThemes()
      })

      row.appendChild(rowButton)
      themesList.appendChild(row)
      themeRowButtons.set(theme.id, rowButton)
    })

    syncThemeRowLabels()
  }

  function syncThemeRowLabels(): void {
    themes.forEach((theme) => {
      const rowButton = themeRowButtons.get(theme.id)
      if (!rowButton) return
      const isActive = theme.id === activeThemeId
      rowButton.textContent = isActive ? `▶ ${theme.name}` : theme.name
      rowButton.classList.toggle('nibble-theme-btn-active', isActive)
      rowButton.setAttribute('aria-label', `Select ${theme.name} theme`)
    })
  }

  function openThemes(opener: HTMLElement): void {
    renderThemeRows()
    themesDialog.open(opener)
  }

  function closeThemes(): void {
    themesDialog.close()
  }

  return {
    setPaused(paused) {
      pauseButton.textContent = paused ? 'Resume' : 'Pause'
      pauseButton.setAttribute('aria-label', paused ? 'Resume game' : 'Pause game')
    },

    setActiveTheme(id) {
      activeThemeId = id
      syncThemeRowLabels()
    },

    setActiveMode(id) {
      activeModeId = id
      syncMenuModeLabels()
    },

    setLevelInfo(text) {
      if (text === null) {
        levelInfoLabel.hidden = true
        levelInfoLabel.textContent = ''
        return
      }
      levelInfoLabel.hidden = false
      levelInfoLabel.textContent = text
    },

    setMuted(muted) {
      syncSoundLabel(muted)
    },

    setTouchControls(enabled) {
      syncTouchPadLabel(enabled)
      syncTouchPadVisibility(enabled)
    },

    updateThemes(nextThemes) {
      themes = nextThemes
      if (!themesOverlay.hidden) renderThemeRows()
    },

    showMenu() {
      displayMenu(null)
    },

    dispose() {
      bar.remove()
      dpad.remove()
      document.documentElement.classList.remove('nibble-touchpad-on')
      menuLayer.remove()
      themesOverlay.remove()
    },
  }
}

function injectStyles(): void {
  if (document.getElementById(STYLE_ELEMENT_ID)) return

  const style = document.createElement('style')
  style.id = STYLE_ELEMENT_ID
  style.textContent = `
    #ui-root {
      font-family: 'JetBrains Mono', 'Courier New', ui-monospace, monospace;
      color: #c4cfa1;
      width: 100%;
      max-width: 100vmin;
    }
    /* Overlay/menu layers escape #ui-root's max-width via position: fixed,
       so #ui-root's own width constraint above only really governs the
       normal-flow control bar; index.html's #ui-root max-width rule (keyed
       to the same --nibble-stage-size as the canvas) is what actually caps
       the bar on mobile. */
    .nibble-bar {
      display: flex;
      flex-wrap: wrap;
      gap: 0.5rem;
      justify-content: center;
      align-items: center;
      padding: 0.5rem 0.25rem;
      row-gap: 0.4rem;
    }
    .nibble-btn {
      background: #1a1c16;
      color: #c4cfa1;
      border: 1px solid #c4cfa1;
      border-radius: 2px;
      padding: 0.4rem 0.75rem;
      font: inherit;
      font-size: 0.85rem;
      letter-spacing: 0.05em;
      text-transform: uppercase;
      cursor: pointer;
      min-height: 44px;
      box-sizing: border-box;
      touch-action: manipulation;
    }
    .nibble-btn:hover,
    .nibble-btn:focus-visible {
      background: #c4cfa1;
      color: #1a1c16;
      outline: none;
    }
    .nibble-btn:focus-visible {
      outline: 2px solid #e8f0c4;
      outline-offset: 2px;
    }
    .nibble-btn[aria-pressed='false'] {
      opacity: 0.75;
    }
    .nibble-level-info {
      display: inline-flex;
      align-items: center;
      color: #c4cfa1;
      padding: 0.4rem 0.25rem;
      font-size: 0.85rem;
      letter-spacing: 0.05em;
      text-transform: uppercase;
      user-select: none;
      min-height: 44px;
      box-sizing: border-box;
      white-space: nowrap;
    }
    /* --- narrow-phone tightening (bar must never horizontally scroll) --- */
    @media (max-width: 480px) {
      .nibble-bar {
        gap: 0.35rem;
        padding: 0.4rem 0.15rem;
      }
      .nibble-btn {
        padding: 0.35rem 0.55rem;
        font-size: 0.75rem;
      }
      .nibble-level-info {
        padding: 0.35rem 0.5rem;
        font-size: 0.75rem;
      }
    }
    /* --- on-screen D-pad ---------------------------------------------
       Portrait/normal: normal document flow, directly below the bar,
       centered — index.html grows --nibble-bar-allowance under
       html.nibble-touchpad-on (toggled by setTouchControls) so the board,
       bar, and pad all fit with zero scrolling.
       Landscape (short viewport): anchored to the bottom-right thumb zone
       via position: fixed instead of growing the allowance, since squeezing
       more vertical chrome there would shrink the board below playable size;
       see the @media (max-height: 480px) override below. */
    .nibble-dpad {
      display: grid;
      grid-template-columns: 64px 64px 64px;
      grid-template-rows: 64px 64px;
      grid-template-areas:
        '.    up    .'
        'left down  right';
      gap: 0.4rem;
      justify-content: center;
      margin: 0.5rem auto 0.75rem;
      touch-action: manipulation;
    }
    .nibble-dpad-btn {
      display: flex;
      align-items: center;
      justify-content: center;
      width: 64px;
      height: 64px;
      background: rgba(26, 28, 22, 0.55);
      color: #c4cfa1;
      border: 1px solid rgba(196, 207, 161, 0.8);
      border-radius: 8px;
      font-size: 1.5rem;
      line-height: 1;
      cursor: pointer;
      box-sizing: border-box;
      touch-action: manipulation;
      -webkit-user-select: none;
      user-select: none;
    }
    .nibble-dpad-btn-up { grid-area: up; }
    .nibble-dpad-btn-left { grid-area: left; }
    .nibble-dpad-btn-right { grid-area: right; }
    .nibble-dpad-btn-down { grid-area: down; }
    .nibble-dpad-btn:hover,
    .nibble-dpad-btn:focus-visible {
      background: rgba(196, 207, 161, 0.25);
      outline: none;
    }
    .nibble-dpad-btn:focus-visible {
      outline: 2px solid #e8f0c4;
      outline-offset: 2px;
    }
    .nibble-dpad-btn-pressed {
      background: #c4cfa1;
      color: #1a1c16;
    }
    /* Landscape / short viewport: fixed thumb-zone corner instead of extra
       in-flow height, semi-translucent so it blocks as little as possible,
       safe-area-inset aware for notched devices held sideways. */
    @media (max-height: 480px) {
      .nibble-dpad {
        position: fixed;
        right: max(0.75rem, env(safe-area-inset-right));
        bottom: max(0.75rem, env(safe-area-inset-bottom));
        margin: 0;
        z-index: 4;
        opacity: 0.85;
      }
    }
    /* --- main menu screen ------------------------------------------- */
    .nibble-menu {
      position: fixed;
      inset: 0;
      z-index: 5;
      display: flex;
      align-items: center;
      justify-content: center;
      overflow-y: auto;
      /* #12140f is the guaranteed-visible fallback: if bg.png 404s the
         gradient still paints (solid colors under it), and if the browser
         can't paint the gradient at all this background-color still reads. */
      background-color: #12140f;
      background-image: linear-gradient(180deg, rgba(10,11,8,0.55) 0%, rgba(10,11,8,0.75) 55%, rgba(10,11,8,0.92) 100%),
        var(--nibble-menu-backdrop, none);
      background-size: cover;
      background-position: center;
      padding: max(2rem, env(safe-area-inset-top)) max(1rem, env(safe-area-inset-right))
        max(2rem, env(safe-area-inset-bottom)) max(1rem, env(safe-area-inset-left));
      box-sizing: border-box;
    }
    .nibble-menu-column {
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: 0.5rem;
      width: 100%;
      max-width: 22rem;
      /* Belt-and-braces for the centered-flex-with-overflow quirk in some
         engines (content can otherwise clip at the top when it overflows a
         vertically-centered flex parent): a shrink-safe margin keeps the
         column from ever being pinned flush under the viewport top edge. */
      margin: auto 0;
    }
    /* Short viewports (landscape phones): let the menu column pack from the
       top instead of centering, so scrolling reaches all content predictably
       and nothing hides above the fold. */
    @media (max-height: 480px) {
      .nibble-menu {
        align-items: flex-start;
      }
      .nibble-menu-column {
        margin: 0.5rem 0;
      }
    }
    .nibble-menu-logo {
      width: 96px;
      height: 96px;
      margin-bottom: 0.5rem;
      filter: drop-shadow(0 6px 14px rgba(0, 0, 0, 0.55));
    }
    .nibble-menu-wordmark {
      margin: 0;
      font-family: 'JetBrains Mono', 'Courier New', ui-monospace, monospace;
      font-size: clamp(2.25rem, 9vw, 3.25rem);
      font-weight: 700;
      letter-spacing: 0.3em;
      color: #c4cfa1;
      text-shadow: 0 2px 18px rgba(196, 207, 161, 0.35), 0 2px 4px rgba(0, 0, 0, 0.6);
      text-align: center;
    }
    .nibble-menu-tagline {
      margin: 0 0 1.5rem;
      font-size: 0.85rem;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: #e8f0c4;
      opacity: 0.85;
      text-align: center;
    }
    .nibble-menu-buttons {
      display: flex;
      flex-direction: column;
      gap: 0.6rem;
      width: 100%;
    }
    .nibble-menu-btn {
      width: 100%;
      background: rgba(26, 28, 22, 0.85);
      color: #c4cfa1;
      border: 1px solid #c4cfa1;
      border-radius: 4px;
      padding: 0.85rem 1rem;
      font: inherit;
      font-size: 0.95rem;
      font-weight: 600;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      text-align: center;
      cursor: pointer;
      min-height: 48px;
      box-sizing: border-box;
      touch-action: manipulation;
    }
    .nibble-menu-btn:hover,
    .nibble-menu-btn:focus-visible {
      background: #c4cfa1;
      color: #1a1c16;
      outline: none;
    }
    .nibble-menu-btn:focus-visible {
      outline: 2px solid #e8f0c4;
      outline-offset: 2px;
    }
    .nibble-menu-btn-play {
      border-color: #e8f0c4;
      background: rgba(196, 207, 161, 0.12);
    }
    .nibble-menu-btn-active {
      border-width: 2px;
      color: #e8f0c4;
    }
    .nibble-menu-resume {
      margin-top: 1rem;
      background: transparent;
      color: #c4cfa1;
      border: none;
      padding: 0.4rem 0.75rem;
      font: inherit;
      font-size: 0.8rem;
      letter-spacing: 0.1em;
      text-transform: uppercase;
      text-decoration: underline;
      text-underline-offset: 3px;
      opacity: 0.75;
      cursor: pointer;
      min-height: 44px;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      box-sizing: border-box;
      touch-action: manipulation;
    }
    .nibble-menu-resume:hover,
    .nibble-menu-resume:focus-visible {
      opacity: 1;
      outline: none;
    }
    .nibble-menu-resume:focus-visible {
      outline: 2px solid #e8f0c4;
      outline-offset: 2px;
    }
    .nibble-overlay {
      position: fixed;
      inset: 0;
      background: rgba(0, 0, 0, 0.6);
      display: flex;
      align-items: center;
      justify-content: center;
      z-index: 10;
      overflow-y: auto;
      padding: max(1rem, env(safe-area-inset-top)) max(1rem, env(safe-area-inset-right))
        max(1rem, env(safe-area-inset-bottom)) max(1rem, env(safe-area-inset-left));
      box-sizing: border-box;
    }
    .nibble-panel {
      background: #1a1c16;
      border: 2px solid #c4cfa1;
      border-radius: 4px;
      padding: 1.25rem;
      min-width: 240px;
      width: 100%;
      max-width: min(92vw, 420px);
      max-height: 85vh;
      max-height: 85dvh;
      overflow-y: auto;
      box-sizing: border-box;
      display: flex;
      flex-direction: column;
      gap: 0.75rem;
      margin: auto;
    }
    /* Short viewports (landscape phones): same reasoning as .nibble-menu —
       pack from the top so an overflowing panel scrolls predictably instead
       of relying on centered-flex-with-overflow behavior. */
    @media (max-height: 480px) {
      .nibble-overlay {
        align-items: flex-start;
      }
      .nibble-panel {
        margin: 0.5rem auto;
      }
    }
    .nibble-panel-title {
      margin: 0;
      font-size: 1rem;
      text-transform: uppercase;
      letter-spacing: 0.1em;
      text-align: center;
    }
    .nibble-themes-list {
      list-style: none;
      margin: 0;
      padding: 0;
      display: flex;
      flex-direction: column;
      gap: 0.25rem;
      max-height: 40vh;
      overflow-y: auto;
    }
    .nibble-themes-row {
      display: flex;
    }
    .nibble-themes-empty {
      text-align: center;
      opacity: 0.7;
      padding: 0.5rem 0;
    }
    .nibble-theme-btn {
      flex: 1;
      background: #1a1c16;
      color: #c4cfa1;
      border: 1px solid #c4cfa1;
      border-radius: 2px;
      padding: 0.4rem 0.6rem;
      font: inherit;
      font-size: 0.85rem;
      letter-spacing: 0.05em;
      text-align: left;
      cursor: pointer;
      min-height: 44px;
      box-sizing: border-box;
      touch-action: manipulation;
    }
    .nibble-theme-btn:hover,
    .nibble-theme-btn:focus-visible {
      background: #2a2d22;
      outline: none;
    }
    .nibble-theme-btn:focus-visible {
      outline: 2px solid #e8f0c4;
      outline-offset: 2px;
    }
    .nibble-theme-btn-active {
      border-color: #e8f0c4;
      color: #e8f0c4;
      font-weight: bold;
    }
    @media (prefers-reduced-motion: no-preference) {
      .nibble-btn,
      .nibble-menu-btn,
      .nibble-menu-resume,
      .nibble-theme-btn {
        transition: background-color 120ms ease, color 120ms ease, opacity 120ms ease;
      }
      .nibble-overlay {
        transition: opacity 120ms ease;
      }
      .nibble-panel {
        transition: transform 120ms ease;
      }
    }
    /* The hidden attribute only maps to a UA-stylesheet display: none, which
       author display rules (e.g. .nibble-menu's / .nibble-overlay's flex)
       silently override — without this reset the menu and every overlay
       renders permanently open. */
    [hidden] {
      display: none !important;
    }
  `
  document.head.appendChild(style)
}
